# Generated by Django 5.0.1 on 2024-01-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название Товара')),
                ('description', models.CharField(max_length=50, verbose_name='Описание Товара')),
                ('price', models.IntegerField(max_length=50, verbose_name='Цена Товара')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Изображение')),
            ],
        ),
    ]
