# Generated by Django 5.0.1 on 2024-01-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_list',
            name='price',
            field=models.IntegerField(verbose_name='Цена Товара'),
        ),
    ]
