# Generated by Django 5.0.1 on 2024-01-18 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_shop_list_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop_list',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
