# Generated by Django 5.0.1 on 2024-01-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shop_list_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_list',
            name='description',
            field=models.CharField(max_length=250, verbose_name='Описание Товара'),
        ),
    ]
